name: Code Linting

# Description:
# - This workflow runs linting on the codebase, fails if linting does not pass.

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install dependencies
        run: pnpm install

      - name: Lint Typescript
        run: pnpm lint
